/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Grant
 */
//altering master branch and then pulling into another branch test
import javax.swing.*;
public class DoctorUI extends javax.swing.JFrame {

    /**
     * Creates new form DoctorUI
     */
    public DoctorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        DoctorUI = new javax.swing.JTabbedPane();
        ViewPatientListTab = new javax.swing.JScrollPane();
        PatientList = new javax.swing.JList();
        RegisterPatient = new javax.swing.JPanel();
        patientNameLabel = new javax.swing.JLabel();
        patientEmailLabel = new javax.swing.JLabel();
        patientAddressLabel = new javax.swing.JLabel();
        patientPhoneLabel = new javax.swing.JLabel();
        patientPassLabel = new javax.swing.JLabel();
        patientConfirmLabel = new javax.swing.JLabel();
        patientRegisterButton = new javax.swing.JButton();
        patientNameField = new javax.swing.JTextField();
        patienEmailField = new javax.swing.JTextField();
        patientAddressField = new javax.swing.JTextField();
        patientPhoneField = new javax.swing.JTextField();
        patientPassField = new javax.swing.JTextField();
        patientConfirmField = new javax.swing.JTextField();
        EditProfile = new javax.swing.JPanel();
        doctorNameLabel = new javax.swing.JLabel();
        doctorEmailLabel = new javax.swing.JLabel();
        doctorAddressLabel = new javax.swing.JLabel();
        doctorHospitalLabel = new javax.swing.JLabel();
        doctorSecretLabel = new javax.swing.JLabel();
        doctorAnswerLabel = new javax.swing.JLabel();
        doctorPassLabel = new javax.swing.JLabel();
        doctorConfirmLabel = new javax.swing.JLabel();
        doctorSubmitButton = new javax.swing.JButton();
        doctorNameField = new javax.swing.JTextField();
        doctorEmailField = new javax.swing.JTextField();
        doctorAddressField = new javax.swing.JTextField();
        doctorHospitalField = new javax.swing.JTextField();
        doctorSecretField = new javax.swing.JTextField();
        doctorAnswerField = new javax.swing.JTextField();
        invalidPassLabel = new javax.swing.JLabel();
        doctorCurrentName = new javax.swing.JLabel();
        doctorCurrentEmail = new javax.swing.JLabel();
        doctorCurrentAddress = new javax.swing.JLabel();
        doctorCurrentHospital = new javax.swing.JLabel();
        doctorCurrentSecret = new javax.swing.JLabel();
        doctorCurrentAnswer = new javax.swing.JLabel();
        doctorPassField = new javax.swing.JPasswordField();
        doctorConfirmField = new javax.swing.JPasswordField();
        doctorPhoneLabel = new javax.swing.JLabel();
        doctorCurrentPhone = new javax.swing.JLabel();
        doctorPhoneField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PatientList.setBackground(new java.awt.Color(204, 204, 255));
        PatientList.setModel(listModel);
        ViewPatientListTab.setViewportView(PatientList);

        DoctorUI.addTab("View Patient List", ViewPatientListTab);

        RegisterPatient.setBackground(new java.awt.Color(204, 204, 255));

        patientNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        patientNameLabel.setText("Name");

        patientEmailLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        patientEmailLabel.setText("Email");

        patientAddressLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        patientAddressLabel.setText("Address");

        patientPhoneLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        patientPhoneLabel.setText("Phone Number");

        patientPassLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        patientPassLabel.setText("Password");

        patientConfirmLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        patientConfirmLabel.setText("Confirm Password");

        patientRegisterButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        patientRegisterButton.setText("Submit");
        patientRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientRegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterPatientLayout = new javax.swing.GroupLayout(RegisterPatient);
        RegisterPatient.setLayout(RegisterPatientLayout);
        RegisterPatientLayout.setHorizontalGroup(
            RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPatientLayout.createSequentialGroup()
                .addGroup(RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterPatientLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientEmailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientAddressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientPhoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientPassLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientConfirmLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(38, 38, 38)
                        .addGroup(RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patienEmailField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientAddressField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientPhoneField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientPassField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientConfirmField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegisterPatientLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(patientRegisterButton)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        RegisterPatientLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {patienEmailField, patientAddressField, patientConfirmField, patientNameField, patientPassField, patientPhoneField});

        RegisterPatientLayout.setVerticalGroup(
            RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLabel)
                    .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientEmailLabel)
                    .addComponent(patienEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientAddressLabel)
                    .addComponent(patientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPhoneLabel)
                    .addComponent(patientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPassLabel)
                    .addComponent(patientPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientConfirmLabel)
                    .addComponent(patientConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(patientRegisterButton)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        DoctorUI.addTab("Register Patient", RegisterPatient);

        EditProfile.setBackground(new java.awt.Color(204, 204, 255));

        doctorNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doctorNameLabel.setText("Name");

        doctorEmailLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doctorEmailLabel.setText("Email");

        doctorAddressLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doctorAddressLabel.setText("Address");

        doctorHospitalLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doctorHospitalLabel.setText("Hospital");

        doctorSecretLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doctorSecretLabel.setText("Secret Question");

        doctorAnswerLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doctorAnswerLabel.setText("Secret Question Answer");

        doctorPassLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doctorPassLabel.setText("Password");

        doctorConfirmLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doctorConfirmLabel.setText("Confirm Password");

        doctorSubmitButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doctorSubmitButton.setText("Submit");
        doctorSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorSubmitButtonActionPerformed(evt);
            }
        });

        invalidPassLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        invalidPassLabel.setForeground(new java.awt.Color(204, 0, 0));

        doctorCurrentName.setText(doc.getName());

        doctorCurrentEmail.setText(doc.getEmail());

        doctorCurrentAddress.setText(doc.getAddress());

        doctorCurrentHospital.setText(doc.getHospital());

        doctorCurrentSecret.setText(doc.getSecret());

        doctorCurrentAnswer.setText(doc.getAnswer());

        doctorPhoneLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doctorPhoneLabel.setText("Phone");

        doctorCurrentPhone.setText(doc.getPhone());

        doctorPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPhoneFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditProfileLayout = new javax.swing.GroupLayout(EditProfile);
        EditProfile.setLayout(EditProfileLayout);
        EditProfileLayout.setHorizontalGroup(
            EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditProfileLayout.createSequentialGroup()
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditProfileLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doctorEmailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doctorAddressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doctorPhoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doctorHospitalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doctorSecretLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(EditProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(doctorAnswerLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPassLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doctorConfirmLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorCurrentName)
                    .addComponent(doctorCurrentEmail)
                    .addComponent(doctorCurrentAddress)
                    .addComponent(doctorCurrentPhone)
                    .addComponent(doctorCurrentHospital)
                    .addComponent(doctorCurrentSecret)
                    .addComponent(doctorCurrentAnswer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorHospitalField)
                    .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(doctorAddressField)
                        .addComponent(doctorEmailField)
                        .addComponent(doctorNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addComponent(doctorAnswerField)
                        .addComponent(doctorSecretField)
                        .addComponent(doctorPassField)
                        .addComponent(doctorConfirmField)
                        .addComponent(doctorPhoneField)))
                .addGap(50, 50, 50))
            .addGroup(EditProfileLayout.createSequentialGroup()
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditProfileLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(doctorSubmitButton))
                    .addGroup(EditProfileLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(invalidPassLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EditProfileLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {doctorAddressField, doctorAnswerField, doctorConfirmField, doctorEmailField, doctorHospitalField, doctorNameField, doctorPassField, doctorSecretField});

        EditProfileLayout.setVerticalGroup(
            EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorNameLabel)
                    .addComponent(doctorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorCurrentName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorEmailLabel)
                    .addComponent(doctorEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorCurrentEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorAddressLabel)
                    .addComponent(doctorAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorCurrentAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorPhoneLabel)
                    .addComponent(doctorCurrentPhone)
                    .addComponent(doctorPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorHospitalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorHospitalLabel)
                    .addComponent(doctorCurrentHospital))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorSecretField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorSecretLabel)
                        .addComponent(doctorCurrentSecret)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorAnswerLabel)
                        .addComponent(doctorCurrentAnswer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditProfileLayout.createSequentialGroup()
                        .addComponent(doctorPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(invalidPassLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorSubmitButton))
                    .addGroup(EditProfileLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(doctorPassLabel)
                        .addGap(18, 18, 18)
                        .addComponent(doctorConfirmLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        DoctorUI.addTab("Edit Profile", EditProfile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DoctorUI)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorUI)
        );

        pack();
    }// </editor-fold>                        

    private void patientRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        //doc.registerPatient(new Patient(...));
        listModel.addElement(patientNameField.getText());
        patientNameField.setText("");
    }                                                     

    private void doctorSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        invalidPassLabel.setText("");
        if(!(doctorNameField.getText().equals("")))
    	{
    		doc.setName(doctorNameField.getText());
    		doctorNameField.setText("");
    		doctorCurrentName.setText(doc.getName());
    	}
    	if(!(doctorEmailField.getText().equals("")))
    	{
    		doc.setEmail(doctorEmailField.getText());
    		doctorEmailField.setText("");
    		doctorCurrentEmail.setText(doc.getEmail());
    	}
    	if(!(doctorAddressField.getText().equals("")))
    	{
    		doc.setAddress(doctorAddressField.getText());
    		doctorAddressField.setText("");
    		doctorCurrentAddress.setText(doc.getAddress());
    	}
    	if(!(doctorPhoneField.getText().equals("")))
    	{
    		doc.setPhoneNumber(doctorPhoneField.getText());
    		doctorPhoneField.setText("");
    		doctorCurrentPhone.setText(doc.getPhone());
    	}
    	if(!(doctorHospitalField.getText().equals("")))
    	{
    		doc.setHospital(doctorHospitalField.getText());
    		doctorHospitalField.setText("");
    		doctorCurrentHospital.setText(doc.getHospital());
    	}
    	if(!(doctorSecretField.getText().equals("")))
    	{
    		doc.setSecret(doctorSecretField.getText());
    		doctorSecretField.setText("");
    		doctorCurrentSecret.setText(doc.getSecret());
    	}
    	if(!(doctorAnswerField.getText().equals("")))
    	{
    		doc.setAnswer(doctorAnswerField.getText());
    		doctorAnswerField.setText("");
    		doctorCurrentAnswer.setText(doc.getAnswer());
    	}
    	if(!(doctorPassField.getText().equals("")))
    	{
    		if(doctorPassField.getText().equals(doctorConfirmField.getText()))
    		{
    			doc.setPassword(doctorPassField.getText());
                        
    		}
    		else
    		{
                        invalidPassLabel.setText("The passwords do not match");
    		}
                doctorPassField.setText("");
                doctorConfirmField.setText("");
    	}
    }                                                  

    private void doctorPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorUI().setVisible(true);
            }
        }); 
    } */

    // Variables declaration - do not modify                     
    private javax.swing.JTabbedPane DoctorUI;
    private javax.swing.JPanel EditProfile;
    private javax.swing.JList PatientList;
    private javax.swing.JPanel RegisterPatient;
    private javax.swing.JScrollPane ViewPatientListTab;
    private javax.swing.JTextField doctorAddressField;
    private javax.swing.JLabel doctorAddressLabel;
    private javax.swing.JTextField doctorAnswerField;
    private javax.swing.JLabel doctorAnswerLabel;
    private javax.swing.JPasswordField doctorConfirmField;
    private javax.swing.JLabel doctorConfirmLabel;
    private javax.swing.JLabel doctorCurrentAddress;
    private javax.swing.JLabel doctorCurrentAnswer;
    private javax.swing.JLabel doctorCurrentEmail;
    private javax.swing.JLabel doctorCurrentHospital;
    private javax.swing.JLabel doctorCurrentName;
    private javax.swing.JLabel doctorCurrentPhone;
    private javax.swing.JLabel doctorCurrentSecret;
    private javax.swing.JTextField doctorEmailField;
    private javax.swing.JLabel doctorEmailLabel;
    private javax.swing.JTextField doctorHospitalField;
    private javax.swing.JLabel doctorHospitalLabel;
    private javax.swing.JTextField doctorNameField;
    private javax.swing.JLabel doctorNameLabel;
    private javax.swing.JPasswordField doctorPassField;
    private javax.swing.JLabel doctorPassLabel;
    private javax.swing.JTextField doctorPhoneField;
    private javax.swing.JLabel doctorPhoneLabel;
    private javax.swing.JTextField doctorSecretField;
    private javax.swing.JLabel doctorSecretLabel;
    private javax.swing.JButton doctorSubmitButton;
    private javax.swing.JLabel invalidPassLabel;
    private javax.swing.JTextField patienEmailField;
    private javax.swing.JTextField patientAddressField;
    private javax.swing.JLabel patientAddressLabel;
    private javax.swing.JTextField patientConfirmField;
    private javax.swing.JLabel patientConfirmLabel;
    private javax.swing.JLabel patientEmailLabel;
    private javax.swing.JTextField patientNameField;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JTextField patientPassField;
    private javax.swing.JLabel patientPassLabel;
    private javax.swing.JTextField patientPhoneField;
    private javax.swing.JLabel patientPhoneLabel;
    private javax.swing.JButton patientRegisterButton;
    // End of variables declaration                   
    private DefaultListModel listModel = new DefaultListModel();
}
    /*private Doctor doc = new Doctor("Bob", "Bob@yahoo.com", "9516 W Bob St", "623-000-9999", 
    		"Bob's Hope Hospital", "testingGit", "What is your mother's maiden name?", "Bobington");
    
   /* private boolean authenticated;
    public User getAuthentication(){
    	return authenticated;
    }
    public boolean isDoctor(){
    	
    }
} */